import { runAgent } from "./runner.ts";
import { agentStore, type AgentConfig } from "./store.ts";
import { sessionManager } from "../session/manager.ts";
import { memoryStore } from "../memory/store.ts";
import { randomUUID } from "node:crypto";
import { safeMessage } from "../errors.ts";

interface BackgroundJob {
  agentId: string;
  runId: string;
  sessionId: string;
  startedAt: string;
  status: "running" | "completed" | "error";
  abortController: AbortController;
  promise: Promise<void>;
}

class AgentScheduler {
  private jobs = new Map<string, BackgroundJob>();
  private intervals = new Map<string, ReturnType<typeof setInterval>>();

  /** List all running background jobs */
  listJobs(): Array<{ agentId: string; runId: string; sessionId: string; startedAt: string; status: string }> {
    return [...this.jobs.values()].map((j) => ({
      agentId: j.agentId,
      runId: j.runId,
      sessionId: j.sessionId,
      startedAt: j.startedAt,
      status: j.status,
    }));
  }

  /** Check if an agent has a running background job */
  isRunning(agentId: string): boolean {
    return [...this.jobs.values()].some((j) => j.agentId === agentId && j.status === "running");
  }

  /** Start a background agent task */
  async startAgent(agentId: string, opts?: { task?: string; workspace?: string }): Promise<{ runId: string; sessionId: string }> {
    const agent = agentStore.get(agentId);
    if (!agent) throw new Error(`Agent not found: ${agentId}`);

    // Check if already running
    if (this.isRunning(agentId)) {
      throw new Error(`Agent "${agent.name}" is already running in background`);
    }

    const { workspaceManager } = await import("../workspace/manager.ts");
    const workspaceContext = opts?.workspace
      ? `\n\n## Workspace\nYou have been assigned this workspace folder:\n\`${opts.workspace}\`\n\nUse workspace tools to explore, read, and write files in this folder.`
      : "\n\n**Note:** No workspace folder is set. If you need to access files, ask the user to set one.";

    const runId = randomUUID().slice(0, 8);
    const sessionId = sessionManager.createSession(agent.modelRef, {
      agentId,
      systemPrompt: agent.systemPrompt,
      thinkingLevel: agent.thinkingLevel,
    }).id;

    const abortController = new AbortController();
    const message = (opts?.task || `[Background Task] You are running autonomously. Complete your assigned task and save a report to memory when done. Current time: ${new Date().toISOString()}`) + workspaceContext;

    // If workspace provided, set it before agent starts
    if (opts?.workspace) {
      workspaceManager.setRoot(opts.workspace);
    }

    // Update agent status
    agentStore.update(agentId, { status: "active" });

    const startedAt = new Date().toISOString();

    const promise = (async () => {
      try {
        const result = await runAgent({
          sessionId,
          message,
          modelRef: agent.modelRef,
          systemPrompt: agent.systemPrompt,
          thinkingLevel: agent.thinkingLevel,
          tools: true,
          skills: agent.skills,
          signal: abortController.signal,
          runId,
        });

        // Update job status
        const j = this.jobs.get(runId);
        if (j) j.status = "completed";

        // Reset agent status
        agentStore.update(agentId, { status: "ready" });

        // Save report to memory store
        const reportContent = [
          `## Background Agent Report: ${agent.name}`,
          ``,
          `**Agent:** ${agent.name} (${agentId})`,
          `**Run ID:** ${runId}`,
          `**Started:** ${startedAt}`,
          `**Completed:** ${new Date().toISOString()}`,
          `**Model:** ${agent.modelRef}`,
          ``,
          `### Result`,
          ``,
          result.text,
          ``,
          `### Session`,
          ``,
          `Session ID: ${sessionId}`,
        ].join("\n");
        memoryStore.save(
          `agent-report-${agentId}-${runId}`,
          reportContent,
          ["agent-report", agentId],
          "project",
          "medium",
        );

        // ✅ Zapisz do MEMORY.md agenta (append — nie nadpisuj)
        const memoryEntry = [
          `## Task Report — ${new Date().toISOString()}`,
          `**Task:** ${opts?.task || "Autonomous background task"}`,
          ``,
          `**Result:**`,
          result.text || "(no output)",
          ``,
          `---`,
          `*Auto-generated by Nova AI*`,
          ``,
        ].join("\n");
        const existing = agentStore.getFile(agentId, "MEMORY.md");
        const existingContent = existing && !(existing as any).missing ? (existing as any).content + "\n\n" : "";
        agentStore.setFile(agentId, "MEMORY.md", existingContent + memoryEntry);

        // ✅ Emisja eventu job_done
        const { emitEvent } = await import("../event-bus/index.ts");
        emitEvent({
          type: "job_done",
          agentId,
          runId,
          sessionId,
          status: "completed",
          text: result.text?.slice(0, 500),
        });

        // ✅ Zapis do global memory store
        memoryStore.save(
          `agent_report_${runId}`,
          `# Agent Report: ${agent.name}\n\n**Run ID:** ${runId}\n**Task:** ${opts?.task || "Autonomous task"}\n\n${result.text || "(no output)"}`,
          ["agent-report", agentId],
          "project",
          "medium",
        );

        console.log(`[AgentScheduler] Agent "${agent.name}" completed background task (${runId})`);

        // Auto-create skill from successful complex tasks
        import("../skill/self-improve.ts").then(({ analyzeForSkill }) => {
          const transcript = sessionManager.getTranscript(sessionId);
          const toolCount = transcript?.filter((m: any) => m.role === "tool").length ?? 0;
          if (toolCount >= 4) {
            analyzeForSkill(transcript as any, agent.modelRef).then((s) => {
              if (s) console.log(`[AgentScheduler] Auto-created skill "${s.name}" from agent run ${runId}`);
            }).catch(() => {});
          }
        }).catch(() => {});

      } catch (e: unknown) {
        const j = this.jobs.get(runId);
        if (j) j.status = "error";

        agentStore.update(agentId, { status: "error" });

        // Save error report
        memoryStore.save(
          `agent-error-${agentId}-${runId}`,
          `## Background Agent Error: ${agent.name}\n\n**Error:** ${safeMessage(e)}\n**Time:** ${new Date().toISOString()}`,
          ["agent-error", agentId],
          "project",
          "high",
        );

        // Emisja eventu job_done z błędem
        const { emitEvent } = await import("../event-bus/index.ts");
        emitEvent({
          type: "job_done",
          agentId,
          runId,
          sessionId,
          status: "error",
          error: safeMessage(e),
        });

        console.error(`[AgentScheduler] Agent "${agent.name}" background task failed: ${safeMessage(e)}`);
      }
    })();

    const job: BackgroundJob = {
      agentId,
      runId,
      sessionId,
      startedAt,
      status: "running",
      abortController,
      promise,
    };

    this.jobs.set(runId, job);
    console.log(`[AgentScheduler] Started background agent "${agent.name}" (${runId})`);

    return { runId, sessionId };
  }

  /** Stop a running background agent */
  async stopAgent(agentId: string): Promise<void> {
    const jobs = [...this.jobs.values()].filter((j) => j.agentId === agentId && j.status === "running");

    if (jobs.length === 0) {
      throw new Error(`Agent "${agentId}" is not running in background`);
    }

    for (const job of jobs) {
      job.abortController.abort();
      job.status = "completed";
      // Wait for the promise to settle
      try { await job.promise; } catch {}
      this.jobs.delete(job.runId);
    }

    agentStore.update(agentId, { status: "ready" });
    console.log(`[AgentScheduler] Stopped background agent "${agentId}"`);
  }

  /** Schedule a recurring background task for an agent */
  scheduleRecurring(agentId: string, intervalMs: number, task?: string): void {
    if (this.intervals.has(agentId)) {
      clearInterval(this.intervals.get(agentId)!);
    }

    const interval = setInterval(async () => {
      if (this.isRunning(agentId)) return; // Skip if already running
      try {
        await this.startAgent(agentId, task);
      } catch (e: unknown) {
        console.warn(`[AgentScheduler] Scheduled task for "${agentId}" failed: ${safeMessage(e)}`);
      }
    }, intervalMs);

    this.intervals.set(agentId, interval);
    console.log(`[AgentScheduler] Scheduled recurring task for "${agentId}" every ${intervalMs}ms`);
  }

  /** Cancel a recurring schedule */
  cancelRecurring(agentId: string): void {
    const interval = this.intervals.get(agentId);
    if (interval) {
      clearInterval(interval);
      this.intervals.delete(agentId);
      console.log(`[AgentScheduler] Cancelled recurring schedule for "${agentId}"`);
    }
  }

  /** Clean up all running jobs and intervals */
  async shutdown(): Promise<void> {
    for (const [agentId] of this.intervals) {
      this.cancelRecurring(agentId);
    }
    for (const job of this.jobs.values()) {
      if (job.status === "running") {
        job.abortController.abort();
        try { await job.promise; } catch {}
      }
    }
    this.jobs.clear();
  }
}

export const agentScheduler = new AgentScheduler();
